import type { Metadata } from 'next'
import './globals.css'
import MainLayout from '@/components/MainLayout'

export const metadata: Metadata = {
  title: 'MGP Magic Post',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">      
      <body>{children}</body>
    </html>
  )
}
