import type { Metadata } from 'next'
import './globals.css'
import UserProvider from '@/hooks/userUser';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'MGP Magic Post',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">      
      <body>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
      <Toaster richColors theme='light' />
    </html>
  )
}
